name: Tests
on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  test:
    uses: ./.github/workflows/test.yml

  deploy:
    needs:
      - test
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yml
